name: Lab3 Assignment Policy to RG

on: workflow_dispatch

env:
  POLICY_NAME: audit-tag-x-all-services

jobs:

  arm-template-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az policy assignment create --name 'audit-all-tags' --scope /subscriptions/737d1672-96a9-4ba4-b12c-8027ef27ab4e --policy $POLICY_NAME -p './arm/lab3/policy_definition/azurepolicy.assing-parm.json'
